server:
  port: 8082

spring:
  application:
    name: feedback-service

  datasource:
    url: jdbc:postgresql://localhost:5432/badminton_db
    username: badminton_user
    password: badminton_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.badminton: DEBUG
